"""Add functions table

Revision ID: 07510a182d3e
Revises: 9c0a54914c78
Create Date: 2024-07-19 09:05:42.135179

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '07510a182d3e'
down_revision = '9c0a54914c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model1', sa.Boolean(), nullable=False),
    sa.Column('model2', sa.Boolean(), nullable=False),
    sa.Column('model3', sa.Boolean(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('functions')
    # ### end Alembic commands ###
