"""added new columns

Revision ID: cd0bef1eab33
Revises: 07510a182d3e
Create Date: 2024-07-25 18:02:41.583520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd0bef1eab33'
down_revision = '07510a182d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercialcustomer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number_of_employees', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('date_hired', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personalcustomer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('client_company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_contact_person_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_contact_person_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_contact_person_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('personalcustomer')
    op.drop_table('employee')
    op.drop_table('competitor')
    op.drop_table('commercialcustomer')
    # ### end Alembic commands ###
